version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prime-capital-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - prime-network

networks:
  prime-network:
    driver: bridge
